int:
	gcc -c arrayInt.c main.c
	gcc -o progArrayInt arrayInt.o main.o
	./progArrayInt 10 > outArrayInt

char:
	gcc -c arrayChar.c main.c
	gcc -o progArrayChar arrayChar.o main.o
	./progArrayChar 100 > outArrayChar

bit:
	gcc -c arrayBit.c main.c
	gcc -o progArrayBit arrayBit.o main.o
	./progArrayBit 100 > outArrayBit